package:
  name: apex{{ environ.get('APEX_PACKAGE_SUFFIX') }}
  version: "{{ environ.get('APEX_BUILD_VERSION') }}"

source:
  git_rev: {{ environ.get('APEX_BUILD_VERSION') }}
  git_url: https://github.com/nvidia/apex.git

requirements:
  build:
  - {{ compiler('c') }} # [win]

  host:
    - python
    - pytorch{{ environ.get('APEX_PACKAGE_SUFFIX') }} >=0.4.1
{{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}

  run:
    - python
    - pytorch{{ environ.get('APEX_PACKAGE_SUFFIX') }} >=0.4.1
{{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}

build:
  number: {{ environ.get('APEX_BUILD_NUMBER') }}
  string: py{{py}}_cu{{ environ['CUDA_VERSION'] }}_{{environ.get('APEX_BUILD_NUMBER')}}
  script: pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .
  script_env:
    - CUDA_VERSION

test:
  source_files:
    - tests/L0
  requires:
    - pytest
  commands:
    pytest .

about:
  home: https://github.com/nvidia/apex
  license: BSD
  license_fild: LICENSE
  summary: 'NVIDIA mixed precision and distributed training for PyTorch'
  
